INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Alfredo', 1000, 8, 0)
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Roberto', 1500, 10, 0)
INSERT INTO TBL_SELLER (NAME, SALARY, BONUS, GENDER) VALUES ('Maria', 1800, 20, 1)